In [1]:
import numpy as np

In [2]:
c = np.arange(10)
d = range(15)

In [3]:
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
range(0, 15)


In [13]:
c = np.arange(15).reshape(3,5)

c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(type(c))

2
(3, 5)
15
int32
4
<class 'numpy.ndarray'>


In [15]:
d = np.array( [2.0, 3.0, 4.0, 5.0] )
print(d)
print(d.dtype)
print(type(d))

[2. 3. 4. 5.]
float64
<class 'numpy.ndarray'>


In [16]:
a = np.eye(8)
dtype=np.float64
a

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
b = np.linspace(-1, 2, 10, endpoint=True)
print(b)

[-1.         -0.66666667 -0.33333333  0.          0.33333333  0.66666667
  1.          1.33333333  1.66666667  2.        ]


In [18]:
b = np.linspace(-1, 2, 10, endpoint=False)
print(b)

[-1.  -0.7 -0.4 -0.1  0.2  0.5  0.8  1.1  1.4  1.7]


In [19]:
d = np.logspace(-1, 2, 10, endpoint=True, base=10)
print(d)

[  0.1          0.21544347   0.46415888   1.           2.15443469
   4.64158883  10.          21.5443469   46.41588834 100.        ]


In [20]:
e = np.fromfunction(lambda i, j: i == j, (4, 4), dtype=int)
e

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [24]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [27]:
b*3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [28]:
b + b

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [29]:
b*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [30]:
print(b)
a = b.transpose()
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
import numpy as np
man = np.arange(50)
even = man[0:45:2]
print(even)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44]


In [22]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
a[1,1]

6

In [25]:
a[0:3,0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [26]:
a = a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [31]:
b = a
b is a

True

In [32]:
b.shape = (3, 5)
print(b)
a.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


(3, 5)

In [33]:
b is a

True

In [34]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [35]:
a = np.arange(10)
c = a[:]
a.shape = (2,5)

print(a)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [36]:
c[1] = -1
print(a)
print(c)

[[ 0 -1  2  3  4]
 [ 5  6  7  8  9]]
[ 0 -1  2  3  4  5  6  7  8  9]


In [37]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
a[a > 5] = 0
a

array([[0, 1, 2, 3],
       [4, 5, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [40]:
print(a)
a[a == 0] = -1
a

[[0 1 2 3]
 [4 5 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[-1,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [41]:
a == -1

array([[ True, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
a = np.arange(12).reshape(3,4)
print(a)
a[np.logical_and(a > 3, a <= 9)] = 0.0
a

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0, 10, 11]])

In [44]:
P = 16
Q = 36
xmin = ymin = 0.0
xmax = ymax = 1.0

x = np.linspace(xmin, xmax, P, endpoint=False)
y = np.linspace(ymin, ymax, Q, endpoint=False)

print(x.shape)
print(y.shape)
y

(16,)
(36,)


array([0.        , 0.02777778, 0.05555556, 0.08333333, 0.11111111,
       0.13888889, 0.16666667, 0.19444444, 0.22222222, 0.25      ,
       0.27777778, 0.30555556, 0.33333333, 0.36111111, 0.38888889,
       0.41666667, 0.44444444, 0.47222222, 0.5       , 0.52777778,
       0.55555556, 0.58333333, 0.61111111, 0.63888889, 0.66666667,
       0.69444444, 0.72222222, 0.75      , 0.77777778, 0.80555556,
       0.83333333, 0.86111111, 0.88888889, 0.91666667, 0.94444444,
       0.97222222])

In [45]:
import time
import numpy as np
P = 32
Q = 64

x = np.linspace(0.0, 1.0, P, endpoint=False)
y = np.linspace(0.0, 1.0, Q, endpoint=False)

In [46]:
t0 = time.time()

g = np.zeros((P, Q))

for i in range(P):
    for j in range(Q):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.10648488998413086 s
